### ISSUE TITLE
Generate a map of CRI participants

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/cri#55]
Srikant requests a method of automatically generating
- a map of Indiana 
- with each participating community marked with a symbol and labeled
- and each community colored according to their progress in the CRI process

## Deadline
This should be finished **before the second-quarter report to OCRA** is made.

## Bonus points
This map could be **shown to the public**, perhaps on the front page of the website or on its own "CRI Participants" page.

## Questions
- @VictoriaMeldrum: What colors should be used to represent steps 1-4?

**Comment by bjpatterson** [comment]
This is the map that we're currently using to show this information.  I'm assuming Srikant is envisioning something similar, just not built by hand any more.

We already have a few instances of overlapping cities and counties, so we've been using both push-pins and area fill to show progress.  The endgame goal for CRI is to service ~200 of the ~300 communities in Indiana, which is going to mean significant overlap within counties.  If we want to start with just one marking method, I lean toward pushpins because of that expectation.

![cmmtyprogress](https://cloud.githubusercontent.com/assets/16689561/23912293/99392d90-08b5-11e7-8f9c-2ec2ca9db011.jpg)

**Comment by bjpatterson** [comment]
One thing to consider: There are several communities in the above map that don't appear anywhere in the website (because they're prospective communities).  If we start enforcing that prospects be put into the system with no clients or surveys set up, we could probably logic the statuses out based on that info.  If we want to require that though, ICI will need to be notified, or there'll be some holes in the map.  That also presents a potential issue of "ghost prospects", the prospects that ultimately chose not to participate.  We'll need to make sure that ex-prospects are handled gracefully so they don't clutter the map.

However we handle prospects, we'll need to standardize it to automate the maps.

**Comment by PhantomWatson** [comment]
Here's my proposal:

- Prospects are handled separately from enrolled communities (separate database table, separate page to manage them)
- When communities are added, they automatically get removed from the list of prospects
- It's assumed that someone (ICI?) will use their best judgement regarding adding and removing prospects
- Regardless, the map could automatically hide prospects that are older than a certain threshold (6 months?), acting on the assumption that any community added as a prospect and then not enrolled for a long time isn't a prospect anymore

**Comment by bjpatterson** [comment]
This could work, with the only downside being that there's an extra lever to teach ICI to pull.

Right now, communities with no payment/survey are pretty safe to consider prospects, with the added benefit that the Notes on the community can be used to track more detailed info.  This isn't a particularly clean/documented implementation, but it has the potential to work as-is without the need to teach ICI any new tricks.

We could migrate prospects to a dedicated prospects space (cleaner), potentially with the understanding that the Notes will migrate with the community if/when they actually enroll.

Any thoughts on ease-of-implementation-and-execution vs. quality-of-design?

**Comment by PhantomWatson** [comment]
Oh, I wasn't sure what actually made a community a "prospect".

It sounds like we could simply say that
- **a "prospect"** is a community that is on the website and who hasn't paid yet, and
- **an "enrolled community"** is one for whom we have a payment recorded

**Comment by bjpatterson** [comment]
Ultimately, I think a prospect is defined as "any community that David suspects might join CRI in the near-ish term," which makes it difficult to pin down formally.

I think your definition is what we were hoping to get ICI on board with. They can just create a new community when communications start, and the site can just assume they're a prospect until they pay.

The only potential snag is going to be handling of stale "prospects." For that, I propose a time threshold. Maybe communities are **excluded as prospects if it's been more than 3 months since the last notes update** (since that's where any ongoing communications should be logged)?

**Comment by PhantomWatson** [comment]
Yeah, so...
- **Active prospects**: Haven't paid and _have_ had activity (anything recorded in the [Activity Log](http://cri.cberdata.org/admin/activity-records)) in the last 90 days
- **Stale prospects**: Haven't paid, _no_ activity in the last 90 days
- **Enrolled**: Have paid

**Comment by PhantomWatson** [comment]
# Coloring proposals
## Area colored
- Counties are completely shaded in
- All other communities represented by dots (MSAs may call for footnotes clarifying that they're MSAs and not cities)

## Stages
### Step One
- **Prospect:** Has record in Communities, no purchases, and activity in last 90 days
- **Enrolled:** Has paid for Step Two
### Step Two & Three
- **Survey phase:** Survey has no responses or is still active
- **Analysis phase:** Survey has collected responses and is now closed
- **Step closed:** Analysis phase criteria met, plus all paid-for presentations have been given
### Step Four
- **Policy development being generated:** Policy dev paid for, not yet delivered
- **Policy development delivered**

## Colors
<img width="335" alt="default" src="https://user-images.githubusercontent.com/1965565/27559135-6a8fe87e-5a8d-11e7-8b6a-8e6ee836ca83.png">

# To do
- [ ] Make `CommunitiesTable::getGps($communityId)` (for non-county community types)
- [ ] Create fields `Communities.lat` and `Communities.lng` (or maybe record this in `areas`?)

**Comment by PhantomWatson** [comment]
# Notes
It appears that regions being shaded (e.g. counties) and markers being placed cannot both happen on the same Google Charts GeoChart. Counties can have markers placed at the location of their county seats, and in the case of two communities then having the same marker position (e.g. one for the county and one for the city that happens to be the county seat), both markers can be visible if county seat markers are larger and underneath city markers.
